name: Update streak stats

on:
  schedule:
    - cron: "0 2 * * *"   # Rozana UTC 2:00 AM (PKT ~7:00 AM)
  workflow_dispatch:      # Manual run button

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write     # Repository write permission

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Streak Stats
        uses: DenverCoder1/github-readme-streak-stats@main
        with:
          user: mjamshaid786
          theme: date_night
          hide_border: "false"
          path: profile/streak.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and Push Streak SVG
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto update streak stats [skip ci]"
          file_pattern: "profile/streak.svg"
